name: build_haydn
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "待操作的底包/xiaomi.eu底包下载地址"
        required: true
        default: 'https://008686.xyz/f/NZ3ug/miui_HAYDN_OS1.0.2.0.UKKCNXM_2fa8bde61d_14.0.zip'
      PORT_URL:
        description: "待操作的移植包下载地址"
        required: true
        
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: 4.上传到 OneDrive
        run: |
            # 部署 rclone
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            wget -O ~/.config/rclone/rclone.conf "${{ secrets.RECLONE }}"
            touch $HOME/123.txt
            rclone sync -P $HOME/123.txt webdav:/HyperOS
